anfibioTumi/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('robotAnfibio.urls'))
]

robotAnfibio/urls.py
from django.urls import path
from . import views

app_name='robotAnfibio'

urlpatterns = [
    path('',views.inicio,name='inicio'),
    path('login',views.log_in,name='login'),
    path('logout',views.log_out,name='logout'),
    path('main',views.main,name='main'),
    path('consola',views.consola,name='consola'),
    path('nuevoUsuario',views.nuevoUsuario,name='nuevoUsuario'),
    path('eliminarUsuario/<str:usuarioId>',views.eliminarUsuario,name='eliminarUsuario'),
    path('nuevaEmbarcacion',views.nuevaEmbarcacion,name='nuevaEmbarcacion'),
    path('eliminarEmbarcacion/<str:embarcacionId>',views.eliminarEmbarcacion,name='eliminarEmbarcacion'),
    path('monitoreo/<str:ind>',views.monitoreo,name='monitoreo'),
    path('trabajo',views.trabajo,name='trabajo'),
    path('estadisticas',views.estadisticas,name='estadisticas'),
    path('galeria/<str:ind>',views.galeria,name='galeria'),
    path('terminarInspeccion',views.terminarInspeccion,name='terminarInspeccion'),
    path('encenderLuces',views.encenderLuces,name='encenderLuces'),
    path('apagarLuces',views.apagarLuces,name='apagarLuces'),
    path('encenderHidrolavadora',views.encenderHidrolavadora,name='encenderHidrolavadora'),
    path('apagarHidrolavadora',views.apagarHidrolavadora,name='encenderCepillos'),
    path('encenderCepillos',views.encendeCepillos,name='apagarCepillos'),
    path('apagarCepillos',views.apagarCepillos,name='apagarHidrolavadora'),
    path('capturarFotoInspeccion',views.capturarFotoInspeccion,name='capturarFotoInspeccion'),
    path('capturarVideoInspeccion',views.capturarVideoInspeccion,name='capturarVideoInspeccion'),
    path('detenerVideoInspeccion',views.detenerVideoInspeccion,name='detenerVideoInspeccion'),
    path('capturarInfoSonar',views.capturarInfoSonar,name='capturarInfoSonar'),
    path('capturarInfoSensorInercial',views.capturarInfoSensorInercial,name='capturarInfoSensorInercial'),
    path('getSizeProject',views.getSizeProject,name='getSizeProject'),
    path('getInfoProject',views.getInfoProject,name='getInforProject'),
    path('getSizeVideo',views.getSizeVideo,name='getSizeVideo'),
    path('comandoRobot',views.comandoRobot,name='comandoRobot')
]

robotAnfibio/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
import datetime

# Create your models here.

class UsuarioAnfibio(AbstractUser):
    codigo_usuario = models.CharField(max_length=32, null=True, blank=True)
    numero_celular = models.CharField(max_length=32, null=True, blank=True)
    imagen_usuario = models.CharField(max_length=32, null=True, blank=True)
    tipo_usuario = models.CharField(max_length=32, null=True, blank=True)

class EmbarcacionesAnfibio(models.Model):
    codigo_embarcacion = models.CharField(max_length=32, null=True, blank=True)
    imagen_embarcacion = models.CharField(max_length=32, null=True, blank=True)

class InspeccionesAnfibio(models.Model):
    codigo_inspeccion = models.CharField(max_length=32, blank=True, null=True)
    ruta_fotos = models.CharField(max_length=128, blank=True, null=True)
    ruta_videos = models.CharField(max_length=128, blank=True, null=True)
    duracion_inspeccion = models.CharField(max_length=128, blank=True, null=True)
    distancia_inspeccion = models.CharField(max_length=128, blank=True, null=True)
    fecha_inspeccion = models.DateTimeField(default=datetime.date.today)
    embarcacion_inspeccion = models.CharField(max_length=128, blank=True, null=True)

robotAnfibio/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse, HttpResponseRedirect
from .models import UsuarioAnfibio, EmbarcacionesAnfibio, InspeccionesAnfibio
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse
import random
import os
import cv2
import subprocess as sp
import datetime
from PIL import Image
import serial

# Create your views here.
ruta_fotos_inspeccion = ''
ruta_videos_inspeccion = ''
counter_fotos = '1'
counter_videos = '1'
app_video = None
inicio_inspeccion = None
fin_inspeccion = None

objSerial = serial.Serial('/dev/ttyACM0',115200)
comandosRobot = {'$OAXBTN3':'$OAX1M','$OAXBTN0':'$OAX3J0A','$OAXBTN1':'$OAX3J0B','$OAXBTN2':'$OAX3JB0'}



def inicio(request):
    return render(request,'robotAnfibio/inicio.html')

@csrf_exempt
def log_in(request):
    if request.method == 'POST':
        usuarioUsername = request.POST.get('usuarioUsername')
        usuarioContra = request.POST.get('usuarioContra')
        usuarioAcceso = authenticate(request,username=usuarioUsername,password=usuarioContra)
        print(usuarioAcceso)
        if usuarioAcceso is not None:
            login(request,usuarioAcceso)
            if usuarioAcceso.tipo_usuario == 'Admin':
                return HttpResponseRedirect(reverse('robotAnfibio:consola'))
            if usuarioAcceso.tipo_usuario == 'Operador':
                return HttpResponseRedirect(reverse('robotAnfibio:main'))
        else:
            return HttpResponseRedirect(reverse('robotAnfibio:login'))
    return render(request,'robotAnfibio/login.html',{
        'usuarios':UsuarioAnfibio.objects.all().order_by('id')
    })

@login_required(login_url='/login')
def log_out(request):
    logout(request)
    return HttpResponseRedirect(reverse('robotAnfibio:login'))

@login_required(login_url='/login')
def main(request):
    return render(request,'robotAnfibio/main.html',{
        'usuario':'Alexander'
    })

def consola(request):
    usuarios_anfibio = UsuarioAnfibio.objects.all().order_by('id')
    embarcaciones_anfibio = EmbarcacionesAnfibio.objects.all().order_by('id')
    return render(request,'robotAnfibio/consola.html',{
        'usuariosAnfibio':usuarios_anfibio,
        'embarcacionesAnfibio':embarcaciones_anfibio,
    })

def eliminarUsuario(request,usuarioId):
    usuario_eliminar = UsuarioAnfibio.objects.get(id=usuarioId)
    codigo_eliminar = str(usuario_eliminar.id)
    while len(codigo_eliminar) < 4:
        codigo_eliminar = '0' + codigo_eliminar
    os.remove(f'./robotAnfibio/static/usr/usr-{codigo_eliminar}.png')
    usuario_eliminar.delete()
    return HttpResponseRedirect(reverse('robotAnfibio:consola'))

def eliminarEmbarcacion(request,embarcacionId):
    embarcacion_eliminar = EmbarcacionesAnfibio.objects.get(id=embarcacionId)
    codigo_eliminar = str(embarcacion_eliminar.id)
    while len(codigo_eliminar) < 4:
        codigo_eliminar = '0' + codigo_eliminar
    os.remove(f'./robotAnfibio/static/emb/emb-{codigo_eliminar}.png')
    embarcacion_eliminar.delete()
    return HttpResponseRedirect(reverse('robotAnfibio:consola'))


@csrf_exempt
def nuevaEmbarcacion(request):
    if request.method == 'POST':
        EmbarcacionesAnfibio().save()
        ult_embarcacion = EmbarcacionesAnfibio.objects.latest('id')
        codigo_embarcacion = str(ult_embarcacion.id)
        while len(codigo_embarcacion) < 4:
            codigo_embarcacion = '0' + codigo_embarcacion
        ult_embarcacion.codigo_embarcacion = 'EMB-' + codigo_embarcacion
        ult_embarcacion.imagen_embarcacion = f'emb/emb-{codigo_embarcacion}.png'
        ult_embarcacion.save()
        Image.open(request.FILES.get('fotoEmbarcacion')).save(f'./robotAnfibio/static/emb/emb-{codigo_embarcacion}.png')
        return HttpResponseRedirect(reverse('robotAnfibio:consola'))

@csrf_exempt
def nuevoUsuario(request):
    if request.method == 'POST':
        nombreUsuario = request.POST.get('nombreUsuario')
        apellidoUsuario = request.POST.get('apellidoUsuario')
        celularUsuario = request.POST.get('celularUsuario')
        emailUsuario = request.POST.get('emailUsuario')
        contraUsuario = request.POST.get('contraUsuario')
        tipoUsuario = request.POST.get('tipoUsuario')
        user_name = nombreUsuario.lower() + apellidoUsuario.lower().capitalize()
        UsuarioAnfibio(
            username=user_name,
            email=emailUsuario,
            first_name=nombreUsuario,
            last_name=apellidoUsuario,
            numero_celular=celularUsuario,
            tipo_usuario=tipoUsuario,
        ).save()
        usuario_activo = UsuarioAnfibio.objects.latest('id')
        usuario_activo.set_password(contraUsuario)
        codigoUsuario = str(usuario_activo.id)
        while len(codigoUsuario) < 4:
            codigoUsuario = '0' + codigoUsuario
        usuario_activo.codigo_usuario = 'USR-' + codigoUsuario
        usuario_activo.imagen_usuario = f'usr/usr-{codigoUsuario}.png'
        usuario_activo.save()
        Image.open(request.FILES.get('fotoUsuario')).save(f'./robotAnfibio/static/usr/usr-{codigoUsuario}.png')
        return HttpResponseRedirect(reverse('robotAnfibio:consola'))
    return render(request,'robotAnfibio/nuevoUsuario.html')

@login_required(login_url='/login')
def monitoreo(request,ind):
    global ruta_fotos_inspeccion
    global ruta_videos_inspeccion
    global inicio_inspeccion
    inspeccionExistente = '0'
    codigo_embarcacion = ind
    try:
        ult_inspeccion = InspeccionesAnfibio.objects.latest('id')
        indicador = str(ult_inspeccion.id + 1)
        inspeccionExistente = '0'
    except:
        InspeccionesAnfibio().save()
        ult_inspeccion = InspeccionesAnfibio.objects.latest('id')
        indicador = str(ult_inspeccion.id)
        inspeccionExistente = '1'
    while len(indicador) < 4:
        indicador = '0' + indicador
    codigo_inspeccion = 'INS-' + indicador
    nombre_directorio = 'ins-' + indicador + '/'
    ruta_directorio_general = './robotAnfibio/static/ins/' + nombre_directorio
    ruta_directorio_videos = ruta_directorio_general + 'videos/'
    ruta_directorio_fotos = ruta_directorio_general + 'fotos/'
    ruta_fotos = 'ins/' + nombre_directorio + 'fotos/'
    ruta_videos = 'ins/' + nombre_directorio + 'videos/'
    os.mkdir(ruta_directorio_general)
    os.mkdir(ruta_directorio_videos)
    os.mkdir(ruta_directorio_fotos)
    if inspeccionExistente == '0':
        InspeccionesAnfibio(codigo_inspeccion=codigo_inspeccion,ruta_fotos=ruta_fotos,ruta_videos=ruta_videos,embarcacion_inspeccion=codigo_embarcacion,duracion_inspeccion='0',distancia_inspeccion='0').save()
    else:
        ult_inspeccion.codigo_inspeccion = codigo_inspeccion
        ult_inspeccion.ruta_fotos = ruta_fotos
        ult_inspeccion.ruta_videos = ruta_videos
        ult_inspeccion.embarcacion_inspeccion = codigo_embarcacion
        ult_inspeccion.duracion_inspeccion = '0'
        ult_inspeccion.distancia_inspeccion = '0'
        ult_inspeccion.save()

    ruta_fotos_inspeccion = ruta_directorio_fotos
    ruta_videos_inspeccion = ruta_directorio_videos
    inicio_inspeccion = datetime.datetime.now()
    return render(request,'robotAnfibio/monitoreo.html')

@login_required(login_url='/login')
def trabajo(request):
    return render(request,'robotAnfibio/trabajo.html',{
        'embarcacionesAnfibio':EmbarcacionesAnfibio.objects.all().order_by('id'),
    })

@login_required(login_url='/login')
def estadisticas(request):
    inspecciones = InspeccionesAnfibio.objects.all().order_by('-id')
    distanciaTotal = 0.00
    nroRecorridos = 0
    duracionTotal = 0.00

    nroRecorridos = str(len(inspecciones))
    for inspecion in inspecciones:
        distanciaTotal = distanciaTotal + float(inspecion.distancia_inspeccion)
    distanciaTotal = round(distanciaTotal,2)
    distanciaTotal = str(distanciaTotal)

    for inspecion in inspecciones:
        duracionTotal = duracionTotal + float(inspecion.duracion_inspeccion)
    duracionTotal = round(duracionTotal,2)
    duracionTotal = str(duracionTotal)
    return render(request,'robotAnfibio/estadisticas.html',{
        'inspecciones':inspecciones,
        'distanciaTotal':distanciaTotal,
        'nroRecorridos':nroRecorridos,
        'duracionTotal':duracionTotal,
    })

@login_required(login_url='/login')
def galeria(request,ind):
    fuentes_fotos = []
    fuentes_videos = []
    if ind == '0':
        inspeccionesTotales = InspeccionesAnfibio.objects.all().order_by('id')
        for inspeccion in inspeccionesTotales:
            fotos_totales = os.listdir('robotAnfibio/static/' + inspeccion.ruta_fotos)
            videos_totales = os.listdir('robotAnfibio/static/' + inspeccion.ruta_videos)
            for foto in fotos_totales:
                if foto[:3] == 'img':
                    fuentes_fotos.append([inspeccion.ruta_fotos + foto, inspeccion.codigo_inspeccion + '-' + (foto.split('.')[0])])
            for video in videos_totales:
                if video[:3] == 'vid':
                    fuentes_videos.append([inspeccion.ruta_videos + video, inspeccion.codigo_inspeccion + '-' + (video.split('.')[0])])
    else:
        inspeccionInfo = InspeccionesAnfibio.objects.get(id=ind)
        fotos_totales = os.listdir('robotAnfibio/static/' + inspeccionInfo.ruta_fotos)
        videos_totales = os.listdir('robotAnfibio/static/' + inspeccionInfo.ruta_videos)
        for foto in fotos_totales:
            if foto[:3] == 'img':
                fuentes_fotos.append([inspeccionInfo.ruta_fotos + foto, inspeccionInfo.codigo_inspeccion + '-' + (foto.split('.')[0])])
        for video in videos_totales:
            if video[:3] == 'vid':
                fuentes_videos.append([inspeccionInfo.ruta_videos + video, inspeccionInfo.codigo_inspeccion + '-' + (video.split('.')[0])])

robotAnfibio/templates/robotAnfibio/consola.html
{% extends "base.html" %}

{% load static %}

{% block extra_js %}
    <script src="{% static 'js/Consola.js' %}"></script>
{% endblock %}

{% block contenido %}
<div id="app">
    <div class="mainContainer">
        <div class="internalMain">
            <div class="logoTumi">
                <img src="{% static 'img/logoSuperior.png' %}" class="logoSuperior">
            </div>
            <div class="position-absolute start-0 top-0" style="background-color: transparent; width: 1280px; height: 120px;">
                <div class="position-absolute top-50 end-0 translate-middle-y" style="margin-right: 30px;">
                    <a style="text-decoration: none;" href="{% url 'robotAnfibio:logout' %}">
                        <button style="width:60px; height:60px; border-radius: 50%; border: solid 2px #96EADA; background-color: transparent;"><i class="fa-solid fa-right-from-bracket fa-2x" style="color: #96EADA;"></i></button>
                    </a>
                </div>
            </div>
            <p class="textoApp" id="mensajeGeneral">Consola de administrador</p>
            <div class="contenedorUsuarios position-absolute top-50 start-50 translate-middle">
                <div class="userContainer" id="opcionesAdmin">  
                    <div class="userInfo justify-content-center">
                        <a style="text-decoration: none;" href="{% url 'robotAnfibio:nuevoUsuario' %}">
                        <button class="contenedorFoto">
                            <i class="fa-solid fa-user-plus fa-7x" style="color: #96EADA;"></i>
                        </button>
                        </a>
                        <div class="infoNombres justify-content-center" id="nom{{ usuario.id }}">
                            <div class="justify-content-center">
                                <p class="nombreUsuario">Crear usuario</p>
                            </div>
                        </div>
                    </div>
                    <div class="userInfo justify-content-center">
                        <button class="contenedorFoto" data-bs-toggle="modal" data-bs-target="#newShip">
                            <i class="fa-solid fa-ship fa-7x" style="color: #96EADA;"></i>
                        </button>
                        <div class="infoNombres justify-content-center" id="nom{{ usuario.id }}">
                            <div class="justify-content-center">
                                <p class="nombreUsuario">Crear embarcacion</p>
                            </div>
                        </div>
                    </div>
                    <div class="userInfo justify-content-center" data-bs-toggle="modal" data-bs-target="#infoUsuarios">
                        <button class="contenedorFoto">
                            <i class="fa-solid fa-users fa-7x" style="color: #96EADA;"></i>
                        </button>
                        <div class="infoNombres justify-content-center" id="nom{{ usuario.id }}">
                            <div class="justify-content-center">
                                <p class="nombreUsuario">Usuarios</p>
                            </div>
                        </div>
                    </div>
                    <div class="userInfo justify-content-center" data-bs-toggle="modal" data-bs-target="#infoBarcos">
                        <button class="contenedorFoto">
                            <i class="fa-solid fa-sailboat fa-7x" style="color: #96EADA;"></i>
                        </button>
                        <div class="infoNombres justify-content-center" id="nom{{ usuario.id }}">
                            <div class="justify-content-center">
                                <p class="nombreUsuario">Embarcaciones</p>
                            </div>
                        </div>
                    </div>
                </ul>
            </div>
            <div class="position-absolute start-0 top-50 translate-middle-y">
                <button id="btnLeft"><i class="fas fa-arrow-circle-left fa-6x" style="color: #96EADA;"></i></button>
            </div>
            <div class="position-absolute end-0 top-50 translate-middle-y">
                <button id="btnRight"><i class="fas fa-arrow-circle-right fa-6x" style="color: #96EADA;"></i></button>
            </div>
            
        </div>
        <div class="position-absolute end-0 bottom-0" style="background-color: transparent; width: 300px; height: 150px;">
            <a style="text-decoration: none;" href="{% url 'robotAnfibio:main' %}"><button class="mainButton">Iniciar</button></a>
        </div>
    </div>
</div>


<div class="modal fade" id="newShip" tabindex="-1" data-bs-backdrop="static" data-bs-keyboard="false">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content" style="background-color: rgba(0,0,0,0.7);">
            <form method="post" action="{% url 'robotAnfibio:nuevaEmbarcacion' %}" enctype="multipart/form-data">
                <div class="modal-header">
                    <h5 class="modal-title textoApp" id="exampleModalLabel">Nueva embarcacion</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="row justify-content-center">
                        <div class="col-8">
                            <p class="labelRegistro">Foto de embarcacion</p>
                            <div class="justify-content-center" style="align-items: center; display: flex; flex-direction: column;">
                                <input class="form-control" type="file" style="width: 250px; background-color: rgba(0,0,0,0.7); color: #96EADA;" name="fotoEmbarcacion">
                            </div>    
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary" data-bs-dismiss="modal" style="background-color: #96EADA;border: #96EADA; color: black;">Cancelar</button>
                    <button type="submit" class="btn btn-primary" style="background-color: #96EADA; border: #96EADA; color: black;" data-bs-dismiss="modal">Guardar</button>
                </div>
            </form>
        </div>
    </div>
</div>

<div class="modal fade" id="infoUsuarios" tabindex="-1" data-bs-backdrop="static" data-bs-keyboard="false">
    <div class="modal-dialog modal-dialog-centered modal-lg">
        <div class="modal-content" style="background-color: rgba(0,0,0,0.7);">
            <div class="modal-header">
                <h5 class="modal-title textoApp" id="exampleModalLabel">Gestion de usuarios</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div style="height: 300px; overflow-y: scroll;">
                    <table class="table table-hover table-dark table-bordered">
                        <thead>
                            <th scope="col">Nombre</th>
                            <th scope="col">Apellido</th>
                            <th scope="col">Codigo</th>
                            <th scope="col">Celular</th>
                            <th scope="col">Eliminar</th>
                        </thead>
                        <tbody class="overflow-y-scroll">
                            {% for usuario in usuariosAnfibio %}
                                <tr>
                                    <td>{{ usuario.first_name }}</td>
                                    <td>{{ usuario.last_name }}</td>
                                    <td scope="row">{{ usuario.codigo_usuario }}</td>
                                    <td>{{ usuario.numero_celular }}</td>
                                    <td class="justify-content-center"><a class="btn btn-danger" style="background-color: #96EADA; color: black; border: #96EADA;" href="{% url 'robotAnfibio:eliminarUsuario' usuario.id %}">Eliminar</a></td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-bs-dismiss="modal" style="background-color: #96EADA;border: #96EADA; color: black;">Cerrar</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="infoBarcos" tabindex="-1" data-bs-backdrop="static" data-bs-keyboard="false">
    <div class="modal-dialog modal-dialog-centered modal-lg">
        <div class="modal-content" style="background-color: rgba(0,0,0,0.7);">
            <div class="modal-header">
                <h5 class="modal-title textoApp" id="exampleModalLabel">Gestion de embarcaciones</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div style="height: 300px; overflow-y: scroll;">
                    <table class="table table-hover table-dark table-bordered table-fixed">
                        <thead>
                            <th scope="col" class="col-6">Codigo</th>
                            <th scope="col" class="col-6">Eliminar</th>
                        </thead>
                        <tbody>
                            {% for embarcacion in embarcacionesAnfibio %}
                                <tr>
                                    <td class="col-6" scope="row">{{ embarcacion.codigo_embarcacion }}</td>
                                    <td class="col-6 justify-content-center"><a class="btn btn-danger" style="background-color: #96EADA; color: black; border: #96EADA;" href="{% url 'robotAnfibio:eliminarEmbarcacion' embarcacion.id %}">Eliminar</a></td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-bs-dismiss="modal" style="background-color: #96EADA;border: #96EADA; color: black;">Cerrar</button>
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block componentes %}


{% endblock %}

robotAnfibio/templates/robotAnfibio/inicio.html
{% extends "base.html" %}

{% load static %}


{% block contenido %}
<div id="app">

</div>
{% endblock %}

{% block componentes %}
    <script type="text/babel" src="{% static 'js/componentes/ButtonRobot.js' %}"></script>
    <script type="text/babel" src="{% static 'js/componentes/Inicio.js' %}"></script>
    
    <!--Insercion de los componentes en el template-->
    <script type="text/babel">
        const root = ReactDOM.createRoot(document.getElementById('app'))
        root.render(<Inicio nombreBoton=' Inicio' icono='fas fa-home' referencia='/login' />);
    </script>
{% endblock %}

robotAnfibio/templates/robotAnfibio/main.html
{% extends "base.html" %}

{% load static %}


{% block contenido %}
<div id="app">
    <div class="appContainerMain">
        <div class="position-absolute start-0 top-0" style="background-color: transparent; width: 1280px; height: 120px;">
            <div class="position-absolute top-50 end-0 translate-middle-y" style="margin-right: 30px;">
                <a style="text-decoration: none;" href="{% url 'robotAnfibio:logout' %}">
                    <button style="width:60px; height:60px; border-radius: 50%; border: solid 2px #96EADA; background-color: transparent;"><i class="fa-solid fa-right-from-bracket fa-2x" style="color: #96EADA;"></i></button>
                </a>
            </div>
        </div>
        <div class="logoTumi">
            <img src="{% static 'img/logoSuperior.png' %}" class="logoSuperiorMain">
        </div>
        {% if user.tipo_usuario == 'Admin' %}
            <div style="margin-top: 20px; margin-left: 0px; display: flex; flex-direction: row;">
                <a style="text-decoration: none;" href="{% url 'robotAnfibio:consola' %}">
                    <button class="leftArrow"><i class="fas fa-arrow-left fa-2x" style="color: white;"></i></button>
                </a>
            </div>
        {% endif %}
        <div class="position-absolute start-0 top-0 textoBienvenido">
            <div class="textoBienvenidoContenedor">
                <p class="textoApp">Bienvenido {{ user.first_name }}</p>
            </div>
        </div>
        <div class="position-absolute start-0 bottom-0">
            <div class="textoMain">
                <p class="textoApp">TUMI ANFIBIO 2022 - Limpieza de barcos</p>
            </div>
        </div>
        <div class="position-absolute start-0 bottom-0">
            <div style="width: 300px; height: 110px;">
                <div id="btnInicio" class="position-absolute top-0 end-0">
                </div>
            </div>
        </div>
        <div class="position-absolute bottom-0 end-0">
            <div class="opcionesMain">
                <div class="opcionMain">
                    <a style="text-decoration: none;" href="{% url 'robotAnfibio:galeria' 0 %}"><i class="fas fa-image fa-lg" style="color:  #96EADA;"></i></a>
                </div>
                <div class="opcionMain">
                    <a style="text-decoration: none;" href="{% url 'robotAnfibio:estadisticas' %}"><i class="fas fa-th-large fa-lg" style="color:  #96EADA;"></i></a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block componentes %}
    <script type="text/babel" src="{% static 'js/componentes/ButtonRobot.js' %}"></script>
    
    <!--Insercion de los componentes en el template-->
    <script type="text/babel">
        const root = ReactDOM.createRoot(document.getElementById('btnInicio'))
        root.render(<ButtonRobot nombreBoton='Iniciar trabajo' icono='' referencia='/trabajo' />);
    </script>
{% endblock %}